# build React static files
FROM node:18-alpine as build
RUN addgroup app && adduser -S -G app app
USER app
WORKDIR /app
RUN mkdir data
COPY ./frontend/package.json ./
COPY ./frontend/package-lock.json ./
RUN npm ci --silent
COPY ./frontend .
ENV VITE_API_URL=http://localhost:80/api
ENV CHOKIDAR_USEPOLLING=true
# CMD npm start
# more efficient way of executing commands without usage of shell process: