# Generated by Django 4.2.1 on 2023-05-22 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("full_title", models.CharField(blank=True, max_length=256, null=True)),
                ("year", models.PositiveIntegerField()),
                ("disc_id", models.SlugField(max_length=255, unique=True)),
                ("cover", models.ImageField(blank=True, null=True, upload_to="covers")),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_full_record", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["title", "year"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("position", models.PositiveSmallIntegerField()),
                ("duration", models.CharField(max_length=12)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="music.album",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SearchTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.TextField(unique=True)),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("album", "album"),
                            ("artist", "artist"),
                            ("track", "track"),
                        ],
                        max_length=24,
                    ),
                ),
                ("last_search", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("term", "model")},
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                        ]
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="music.album",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("disc_id", models.SlugField(max_length=255, unique=True)),
                (
                    "cover",
                    models.ImageField(blank=True, null=True, upload_to="band_covers"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_full_record", models.BooleanField(default=False)),
                (
                    "favorite",
                    models.ManyToManyField(
                        blank=True,
                        related_name="artist_favorite",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="album",
            name="artists",
            field=models.ManyToManyField(related_name="albums", to="music.artist"),
        ),
        migrations.AddField(
            model_name="album",
            name="favorite",
            field=models.ManyToManyField(
                blank=True, related_name="album_favorite", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="genres",
            field=models.ManyToManyField(related_name="albums", to="music.genre"),
        ),
    ]
