# Generated by Django 4.2.1 on 2023-05-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="albums_found",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="artist",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
