# Generated by Django 4.2.1 on 2023-05-18 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("music", "0002_favorites"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="favorite",
            field=models.ManyToManyField(
                blank=True, related_name="album_favourite", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="favorite",
            field=models.ManyToManyField(
                blank=True, related_name="artist_favourite", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Favorites",
        ),
    ]
