# Generated by Django 4.2.1 on 2023-05-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_alter_searchterm_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="cover_ext_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="cover_ext_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
